# Student Model hyperparameters
distill_factor: 3  # tested, -1, 1, 2, 3
num_hidden_layers: 12  # Only necessary if `distill_factor` > 0
num_attention_heads: 8  # Only necessary if `distill_factor` > 0, must divide `embed_dim`
num_conv_pos_embedding_groups: 8  # Only necessary if `distill_factor` > 0
tdnn_dim: (512, 512, 1500)  # Only necessary if `distill_factor` > 0
tdnn_kernel: (5, 3, 3)  # Only necessary if `distill_factor` > 0
tdnn_dilation: (1, 2, 3)  # Only necessary if `distill_factor` > 0
activation_dropout: 0.1
attention_dropout: 0.1
hidden_dropout: 0.1
feat_proj_dropout: 0.1
final_dropout: 0.1
mask_time_prob: 0.075
mask_feature_prob: 0.075
mask_feature_length: 10
layerdrop: 0.1
ctc_loss_reduction: sum