# Teacher Model hyperparameters
activation_dropout: 0.1
attention_dropout: 0.1
hidden_dropout: 0.1
feat_proj_dropout: 0.1
final_dropout: 0.1
mask_time_prob: 0.075
mask_feature_prob: 0.075
mask_feature_length: 10
layerdrop: 0.1
ctc_loss_reduction: sum