# Teacher Model hyperparameters
# activation_dropout (float, optional):
#     The dropout rate for the activation layer. 
# attention_dropout (float, optional):
#     The dropout rate for the attention layer. 
# hidden_dropout (float, optional):
#     The dropout rate for the hidden layer. 
# feat_proj_dropout (float, optional):
#     The dropout rate for the feature projection layer. 
# final_dropout (float, optional):
#     The dropout rate for the final layer. 
# mask_time_prob (float, optional):
#     The probability of masking the time dimension. 
# mask_feature_prob (float, optional):
#     The probability of masking the feature dimension. 
# mask_feature_length (int, optional):
#     The length of the masking of the feature dimension. 
# layerdrop (float, optional):
#     The dropout rate for the layers. 
# ctc_loss_reduction (str, optional):
#     The reduction to use for the CTC loss. 


activation_dropout: 0.1
attention_dropout: 0.1
hidden_dropout: 0.1
feat_proj_dropout: 0.1
final_dropout: 0.1
mask_time_prob: 0.075
mask_feature_prob: 0.075
mask_feature_length: 10
layerdrop: 0.1
ctc_loss_reduction: sum